# Generated by Django 5.1.6 on 2025-03-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=11, unique=True)),
                ('problem_type', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing Issue'), ('feature', 'Feature Request'), ('question', 'General Question'), ('other', 'Other')], max_length=20)),
                ('problem_description', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('submitted_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.client')),
            ],
        ),
    ]
